# Generated by Django 5.2 on 2025-05-07 13:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='genre',
            field=models.CharField(default='Ficción', max_length=50, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='page',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=3, verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='page',
            name='subtitle',
            field=models.CharField(max_length=150, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
